# Jupyter Notebook for the 1st lab session

In [75]:
import numpy as np
numpy.version.version


'2.5.3'

## Warm-Up with NumPy

### Array creation and attributes
This task consists of creating NumPy arrays in the following ways:
* **Manual array creation**
* **Generating arrays with built-in functions**
* **Creating sequences of values**

In [76]:
A = np.array([[1,2],[3,4]])   #Manual array creation
print(f"Array: {A} \nDimensions: {A.ndim} \nShape: {A.shape} \nData type: {A.dtype}")

Array: [[1 2]
 [3 4]] 
Dimensions: 2 
Shape: (2, 2) 
Data type: int64


In [77]:
Z = np.zeros((2,4,5))   #Array of zeros
print(f"Array: {Z} \nDimensions: {Z.ndim} \nShape: {Z.shape} \nData type: {Z.dtype}")

Array: [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]] 
Dimensions: 3 
Shape: (2, 4, 5) 
Data type: float64


In [78]:
O = np.ones((1,3,1), dtype=np.int32)  #Array of ones (int32)
print(f"Array: {O} \nDimensions: {O.ndim} \nShape: {O.shape} \nData type: {O.dtype}")

Array: [[[1]
  [1]
  [1]]] 
Dimensions: 3 
Shape: (1, 3, 1) 
Data type: int32


In [79]:
#let's check the bytes that different dtypes occupy, for the same shape
A = np.full((5,5), 4, dtype=np.float64)
B = np.full((5,5), 4, dtype=np.int8)

print(f"int8 5x5 matrix: {B.nbytes} bytes \nfloat32 5x5 matrix: {A.nbytes} bytes")

int8 5x5 matrix: 25 bytes 
float32 5x5 matrix: 200 bytes


### Universal functions, aggregations and sorting
In this task we'll explore NumPy's core operations for element-wise computation and data aggregation. Two ```2x2 arrays of floats``` will be used to test this code. 
The functions that we're going to explore are:
* **Element-wise operations**
* **Aggregation and axis behavior**
* **Sorting and ranking**

Element-wise operations: Perform basic arithmetic operations between
your arrays, such as addition, subtraction, multiplication, and exponen-
tiation. Compare the outputs to confirm that each operation is applied
to the corresponding elements. Then, apply a few universal functions
(for example, np.exp or np.sqrt) and observe how they affect all entries
simultaneously.

In [80]:
a = np.random.random((2,2)).round(2)
b = np.random.random((2,2)).round(2)
print(a)
print(b)

[[0.89 0.07]
 [0.25 0.07]]
[[0.15 0.99]
 [0.09 0.87]]


In [81]:
a+b

array([[1.04, 1.06],
       [0.34, 0.94]])

In [82]:
a * b

array([[0.1335, 0.0693],
       [0.0225, 0.0609]])

In [83]:
np.power(a,b)

array([[0.98267182, 0.07188645],
       [0.882703  , 0.09890888]])

In [84]:
np.sqrt(b)

array([[0.38729833, 0.99498744],
       [0.3       , 0.93273791]])

Aggregations and axis behavior: Compute the sum, mean, std, and
argmax of your array both globally and along specific axes. Take a look
at the shapes of the results to understand how the choice of the axis
parameter modifies the output.

In [85]:
a.sum()

np.float64(1.28)

In [86]:
a.mean()

np.float64(0.32)

In [87]:
a.std()

np.float64(0.3371943060017473)

In [88]:
b_vsum = b.sum(axis=0)  #sum along the vertical axis
b_vsum

array([0.24, 1.86])

In [89]:
b_vsum.shape

(2,)

In [90]:
b_hsum = b.sum(axis=1)   #sum along the horizontal axis
b_hsum

array([1.14, 0.96])

In [91]:
b_hsum.shape

(2,)

Sorting and ranking: Create a small integer matrix and apply np.sort
along rows and columns. Then use np.argsort to see how the result
changes.

In [92]:
A = np.random.randint(5, size=(3,3))
A

array([[2, 3, 1],
       [2, 2, 4],
       [4, 0, 2]])

In [93]:
np.sort(A)  #default np.sort (works on -1 by default, which is the last axis)

array([[1, 2, 3],
       [2, 2, 4],
       [0, 2, 4]])

In [94]:
np.sort(A, axis=0)

array([[2, 0, 1],
       [2, 2, 2],
       [4, 3, 4]])

In [95]:
np.argsort(A)   #indeces that would sort the array

array([[2, 0, 1],
       [0, 1, 2],
       [1, 2, 0]])

In [96]:
np.argsort(A, axis=0)

array([[0, 2, 0],
       [1, 1, 2],
       [2, 0, 1]])

### Broadcasting

In [97]:
D = np.array([[0,3,6,6],
              [1,2,5,7],
              [2,4,4,8]], dtype=np.float64)

mn = np.min(D, axis=0)
mx = np.max(D, axis=0)

print(mn)
print(mx)

[0. 2. 4. 6.]
[2. 4. 6. 8.]


### Indexing & views vs copies

## Iris Dataset with NumPy
In this part of the lab, you will load the Iris dataset, extract its features
and labels, and analyze it using NumPy’s statistical tools.

### Feature extraction and statistical analysis
We'll work with the Iris dataset to practice basic data handling and statistical analysis using NumPy. We'll then:
* **Building the feature and label arrays**
* **Computing global statistics**
* **Analyzing statistics by species**

In [98]:
X = np.genfromtxt("../Data/iris.csv", delimiter=",", usecols=(0,1,2,3), dtype=float)
y = np.genfromtxt("../Data/iris.csv", delimiter=",", usecols=4, dtype=str)

**Building the feature and label arrays**: Once you have loaded the
dataset into memory, verify the data types and shapes of both arrays.

In [99]:
print("Analyzing the feature array")
print(f"Shape: {X.shape}\nData types: {X.dtype}")
print("===================")
print("Analyzing the label array")
print(f"Shape: {y.shape}\nData types: {y.dtype}")

Analyzing the feature array
Shape: (150, 4)
Data types: float64
Analyzing the label array
Shape: (150,)
Data types: <U15


**Computing global statistics**: Using NumPy’s aggregation functions,
compute the mean and standard deviation for each of the four features
across the entire dataset (```sepal length, sepal width, petal length, petal
width```).

In [100]:
print("Global stats:")
feature_names = ["sepal_len", "sepal_width", "petal_len", "petal_width"]
for i, feature in enumerate(feature_names):
    print("============================")
    print(f"feature {feature}:")
    print(f"Mean: {np.mean(X[:, i])}")
    print(f"Std: {np.std(X[:, i])}")


Global stats:
feature sepal_len:
Mean: 5.843333333333334
Std: 0.8253012917851409
feature sepal_width:
Mean: 3.0540000000000003
Std: 0.4321465800705435
feature petal_len:
Mean: 3.758666666666666
Std: 1.7585291834055212
feature petal_width:
Mean: 1.1986666666666668
Std: 0.7606126185881716


**Analyzing statistics by species**: Identify the unique species present
in the dataset and, for each one, create a Boolean mask that selects only
the corresponding samples from X. Compute per-class means and standard
deviations, and examine which features show the most apparent separation
between species.

In [101]:
np.unique(y)    #unique labels

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15')

In [102]:
setosa_msk = y == 'Iris-setosa'
versicolor_msk = y == 'Iris-versicolor'
virginica_msk = y == 'Iris-virginica'

In [109]:
print("Iris-setosa stats:")
for i, feature in enumerate(feature_names):
    print("============================")
    print(f"feature {feature}:")
    print(f"Mean: {np.mean(X[:, i])}")
    print(f"Std: {np.std(X[:, i])}")

Iris-setosa stats:
feature sepal_len:
Mean: 5.843333333333334
Std: 0.8253012917851409
feature sepal_width:
Mean: 3.0540000000000003
Std: 0.4321465800705435
feature petal_len:
Mean: 3.758666666666666
Std: 1.7585291834055212
feature petal_width:
Mean: 1.1986666666666668
Std: 0.7606126185881716


In [108]:
print("Iris-versicolor stats:")
for i, feature in enumerate(feature_names):
    print("============================")
    print(f"feature {feature}:")
    print(f"Mean: {np.mean(X[:, i])}")
    print(f"Std: {np.std(X[:, i])}")

Iris-versicolor stats:
feature sepal_len:
Mean: 5.843333333333334
Std: 0.8253012917851409
feature sepal_width:
Mean: 3.0540000000000003
Std: 0.4321465800705435
feature petal_len:
Mean: 3.758666666666666
Std: 1.7585291834055212
feature petal_width:
Mean: 1.1986666666666668
Std: 0.7606126185881716


In [107]:
print("Iris-virginica stats:")
for i, feature in enumerate(feature_names):
    print("============================")
    print(f"feature {feature}:")
    print(f"Mean: {np.mean(X[:, i])}")
    print(f"Std: {np.std(X[:, i])}")

Iris-virginica stats:
feature sepal_len:
Mean: 5.843333333333334
Std: 0.8253012917851409
feature sepal_width:
Mean: 3.0540000000000003
Std: 0.4321465800705435
feature petal_len:
Mean: 3.758666666666666
Std: 1.7585291834055212
feature petal_width:
Mean: 1.1986666666666668
Std: 0.7606126185881716


### Feature standardization
This step consists of transforming the Iris feature matrix so thath each col (feature) is standardized to have zero mean and unit variance. **This ensures
that all measurements contribute equally to subsequent analyses, regardless of
their original scale.**

**Computing the standardized matrix**
Use NumPy’s aggregation func-
tions to compute the column-wise mean and standard deviation of the
feature matrix X. Then, apply the standardization formula:

$$Z = \frac{X - mean(X)}{std(X)}$$

to create a new matrix Z of the same shape as X. Confirm that the trans-
formation has been applied independently to each feature column.

In [114]:
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)

print(X_mean.shape, X_std.shape)

(4,) (4,)


In [116]:
Z = (X - X_mean)/X_std
print(np.mean(Z))
print(np.std(Z))

-1.3263464400855204e-15
1.0


### Naive single-feature classifier
In this final exercise on the Iris dataset, you will build a simple classifier that
uses only one feature to predict the species of a flower.

In [120]:
classes = np.unique(y)
means = np.vstack([X[y==c].mean(axis=0) for c in classes])
print(means)

[[5.006 3.418 1.464 0.244]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]


In [128]:
from itertools import combinations

class_pairs = np.array(list(combinations(range(len(classes)), 2)))

pair_diffs = np.abs(means[class_pairs[:,0], :] - means[class_pairs[:,1], :])

min_sep_by_feat = np.min(pair_diffs, axis=0)
print(min_sep_by_feat)

best_feat = int(np.argmax(min_sep_by_feat))
best_feat_name = feature_names[best_feat]
print(f"Best feature: {best_feat} ({best_feat_name})")

[0.652 0.204 1.292 0.7  ]
Best feature: 2 (petal_len)


In [130]:
m = means[:,best_feat]
order = np.argsort(m)
m_sorted = m[order]
classes_sorted = classes[order]

print(m_sorted)
print(classes_sorted)

[1.464 4.26  5.552]
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']


In [132]:
t1 = 0.5*(m_sorted[0] + m_sorted[1])
t2 = 0.5*(m_sorted[1] + m_sorted[2])

print(t1,t2)

2.862 4.906


In [135]:
feature_values = X[:, best_feat]
predictions = np.where(feature_values < t1, 0, np.where(feature_values < t2, 1, 2))

prediction_classes = classes_sorted[predictions]

acc = (prediction_classes == y).mean()
print(acc)

0.9466666666666667
